import { Achievement } from '@/types/achievement';

export const ACHIEVEMENTS: Achievement[] = [
  // Streak Achievements
  {
    id: 'first-care',
    name: 'First Care',
    description: 'Care for your buddy for the first time',
    icon: '👶',
    rarity: 'common',
    category: 'streak',
    criteria: { type: 'activity-count', target: 1 },
    pointsReward: 50,
  },
  {
    id: 'getting-consistent',
    name: 'Getting Consistent',
    description: 'Maintain a 3-day care streak',
    icon: '🔥',
    rarity: 'common',
    category: 'streak',
    criteria: { type: 'streak', target: 3 },
    pointsReward: 100,
  },
  {
    id: 'week-warrior',
    name: 'Week Warrior',
    description: 'Maintain a 7-day care streak',
    icon: '⚔️',
    rarity: 'rare',
    category: 'streak',
    criteria: { type: 'streak', target: 7 },
    pointsReward: 250,
  },
  {
    id: 'unstoppable',
    name: 'Unstoppable',
    description: 'Maintain a 30-day care streak',
    icon: '🚀',
    rarity: 'epic',
    category: 'streak',
    criteria: { type: 'streak', target: 30 },
    pointsReward: 1000,
  },
  {
    id: 'centurion',
    name: 'Centurion',
    description: 'Maintain a 100-day care streak',
    icon: '💯',
    rarity: 'legendary',
    category: 'streak',
    criteria: { type: 'streak', target: 100 },
    pointsReward: 5000,
  },

  // Tool Variety Achievements
  {
    id: 'tool-explorer',
    name: 'Tool Explorer',
    description: 'Use 3 different AI tools',
    icon: '🔍',
    rarity: 'common',
    category: 'variety',
    criteria: { type: 'tool-variety', target: 3 },
    pointsReward: 150,
  },
  {
    id: 'swiss-army-knife',
    name: 'Swiss Army Knife',
    description: 'Use all major AI tools',
    icon: '🔪',
    rarity: 'rare',
    category: 'variety',
    criteria: { type: 'tool-variety', target: 4 },
    pointsReward: 300,
  },

  // Milestone Achievements
  {
    id: 'decathlon',
    name: 'Decathlon',
    description: 'Complete 10 care sessions',
    icon: '🏅',
    rarity: 'common',
    category: 'milestone',
    criteria: { type: 'activity-count', target: 10 },
    pointsReward: 200,
  },
  {
    id: 'half-century',
    name: 'Half Century',
    description: 'Complete 50 care sessions',
    icon: '🎯',
    rarity: 'rare',
    category: 'milestone',
    criteria: { type: 'activity-count', target: 50 },
    pointsReward: 500,
  },
  {
    id: 'care-centurion',
    name: 'Care Centurion',
    description: 'Complete 100 care sessions',
    icon: '⭐',
    rarity: 'epic',
    category: 'milestone',
    criteria: { type: 'activity-count', target: 100 },
    pointsReward: 1500,
  },

  // Special Achievements
  {
    id: 'game-changer',
    name: 'Game Changer',
    description: 'Complete 5 critical impact activities',
    icon: '💥',
    rarity: 'rare',
    category: 'special',
    criteria: { type: 'impact', target: 5, impactLevel: 'critical' },
    pointsReward: 400,
  },
  {
    id: 'weekend-grinder',
    name: 'Weekend Grinder',
    description: 'Care for your buddy on 5 weekends',
    icon: '🌅',
    rarity: 'rare',
    category: 'special',
    criteria: { type: 'weekend', target: 5 },
    pointsReward: 350,
  },
  {
    id: 'founding-member',
    name: 'Founding Member',
    description: 'Join during the first week',
    icon: '🌟',
    rarity: 'epic',
    category: 'special',
    criteria: { type: 'special' },
    pointsReward: 500,
  },

  // Buddy Evolution Achievements
  {
    id: 'level-5',
    name: 'Rising Star',
    description: 'Reach buddy level 5',
    icon: '⭐',
    rarity: 'common',
    category: 'milestone',
    criteria: { type: 'special' },
    pointsReward: 250,
  },
  {
    id: 'level-10',
    name: 'Expert Trainer',
    description: 'Reach buddy level 10',
    icon: '🎓',
    rarity: 'rare',
    category: 'milestone',
    criteria: { type: 'special' },
    pointsReward: 750,
  },
  {
    id: 'level-15',
    name: 'Master Trainer',
    description: 'Reach buddy level 15',
    icon: '👑',
    rarity: 'legendary',
    category: 'milestone',
    criteria: { type: 'special' },
    pointsReward: 2000,
  },

  // Perfect Care Achievements
  {
    id: 'perfect-week',
    name: 'Perfect Week',
    description: 'Keep buddy at 100% happiness for 7 days',
    icon: '💯',
    rarity: 'rare',
    category: 'special',
    criteria: { type: 'special' },
    pointsReward: 400,
  },
  {
    id: 'max-stats',
    name: 'Peak Performance',
    description: 'Reach 100 in all buddy stats',
    icon: '🏆',
    rarity: 'epic',
    category: 'special',
    criteria: { type: 'special' },
    pointsReward: 600,
  },
];
